Install CORS package
its-dev-fer/project-spark-api pull request #1
Opened 2024-12-11 13:14 UTC by KiritoKazut0

2024-12-11 18:45 UTC, its-dev-fer commented
Puedes ejecutar `npm version patch` por favor? Eso indicaría la versión 0.0.1

2024-12-11 18:46 UTC, its-dev-fer requested changes

2024-12-11 18:46 UTC, its-dev-fer commented on src/index.ts
Instalas cors pero no los usas con `app.use(....)`

2024-12-13 18:55 UTC, AdriianEnriquez approved these changes

2024-12-13 21:59 UTC, its-dev-fer approved these changes

2024-12-16 18:18 UTC, merged