creacion de los modelos
its-dev-fer/project-spark-api pull request #3
Opened 2024-12-11 19:38 UTC by Isaili

.

2024-12-11 19:47 UTC, its-dev-fer requested changes

2024-12-11 19:47 UTC, its-dev-fer commented on package.json
> +    "spark-project-api": "file:"
Tracking.

2024-12-11 19:47 UTC, its-dev-fer commented on src/Config/conection_database.ts
> +import { Sequelize } from "sequelize";
Typo: DatabaseConnection.ts

2024-12-11 19:47 UTC, its-dev-fer commented on src/Config/conection_database.ts
> +    dialect: "mysql",
postgres

2024-12-11 19:47 UTC, its-dev-fer commented on src/Config/conection_database.ts
> +const sequelize_conexion = new Sequelize(NAME_DATABASE, USERNAME, PASSWORD, {
sequelizeConnection

2024-12-11 19:47 UTC, its-dev-fer commented on src/db/Models/EventType.ts
> +import sequelize_conexion from '../../Config/conection_database';
Tracking.

2024-12-11 19:47 UTC, its-dev-fer commented on src/db/Models/EventType.ts
> +        sequelize:sequelize_conexion,
Tracking.

2024-12-11 19:47 UTC, its-dev-fer commented on src/db/Models/EventType.ts
> +        timestamps: false,
true

2024-12-11 19:47 UTC, its-dev-fer commented on src/db/Models/Events.ts
> +      type: DataTypes.DATEONLY,
Incluir la hora en el tipo de dato

2024-12-11 19:47 UTC, its-dev-fer commented on src/db/Models/Guests.ts
> +      type: DataTypes.STRING(50),
Enum ('Pending', 'Accepted', 'Rejected')

2024-12-12 16:57 UTC, its-dev-fer commented on package.json
> +    "spark-project-api": "file:"
la linea 17, se necesita?

2024-12-12 19:29 UTC, its-dev-fer requested changes

2024-12-12 19:29 UTC, its-dev-fer commented on package.json
> +      "express": "^4.21.2"
se borró la dependencia de sequelize.

2024-12-12 20:03 UTC, its-dev-fer approved these changes

2024-12-12 20:14 UTC, AdriianEnriquez approved these changes

2024-12-12 20:20 UTC, merged